import type { Page } from '@playwright/test';

/** Presentation-only fixture data; no fixture is imported by the application. */
export async function webSession(page: Page, role: 'student' | 'staff' | 'admin', failure = false) {
  await page.addInitScript(() => localStorage.setItem('campusflow.token', 'web-review-only'));
  const now = '2026-09-15T10:00:00Z';
  await page.clock.setFixedTime(new Date(now));
  const user = { id: 'review-user', name: role === 'student' ? 'Amina Yusuf' : role === 'staff' ? 'Daniel Nwosu' : 'Nadia Mensah', email: `${role}@example.test`, role_code: role, department: 'Computer Science', permissions: [], is_active: true };
  const notices = [{ id: 'n1', title: 'Your campus day is ready', body: 'Your timetable and campus services are available in your workspace.', type: 'class.reminder', created_at: now, read_at: null }];
  const entry = { id: 'session-one', date: '2026-09-15', course_code: 'CS204', course_title: 'Interaction design', session_type: 'lecture', starts_at: '11:00', ends_at: '12:30', starts_at_iso: '2026-09-15T11:00:00Z', ends_at_iso: '2026-09-15T12:30:00Z', room_id: 'r1', room_code: 'B204', building_code: 'B', building_name: 'Science & design', floor_name: 'First floor', lecturer: 'Dr. Okafor', minutes_until: 60, is_now: false };
  const buildings = [{ id: 'b1', code: 'A', name: 'Learning centre', lat: 3.863, lng: 11.512, footprint: null, status: 'operational', floor_count: 3, room_count: 18 }, { id: 'b2', code: 'B', name: 'Science & design', lat: 3.864, lng: 11.514, footprint: null, status: 'operational', floor_count: 2, room_count: 12 }, { id: 'b3', code: 'C', name: 'Student services', lat: 3.862, lng: 11.515, footprint: null, status: 'maintenance', floor_count: 2, room_count: 8 }];
  const queues = [{ id: 'q1', room_id: 'r1', room_code: 'B204', room_name: 'Design studio', building_code: 'B', floor_name: 'First floor', room_capacity: 30, admission_capacity: 10, is_active: true, waiting: 6, serving: 2, avg_service_seconds: 300, max_size: 20, requires_proximity_to_join: true, opens_at: null, my_ticket_id: 't1' }];
  const ticket = { ticket: { id: 't1', queue_id: 'q1', ticket_number: 'B-024', status: 'waiting', issued_at: now }, queue: queues[0], people_ahead: 3, eta_seconds: 900, expected_service_at: '2026-09-15T10:15:00Z', check_in_deadline: null, seconds_until_deadline: null, can_check_in: false, can_cancel: true, counts: { waiting: 6, in_service: 2 } };
  const office = { id: 'o1', code: 'SA', name: 'Student affairs', description: 'Student records and campus support.', building_code: 'C', floor_name: 'Ground floor', room_code: 'C101', requires_appointment: false, requires_proximity_to_request: false, is_active: true };
  const summary = { office, counts: { waiting: 4, in_service: 1 }, average_service_minutes: 10, next_ticket_number: 'SA-018', estimated_wait_minutes: 40, is_open_now: true, next_opening: null, expected_window: null, services: [], staff: [] };
  const overview = { users: { active_7d: 1248 }, queues: { configured: 12, active: 8, issued_7d: 834, average_wait_minutes: 12, no_show_rate_7d: 4, busiest_rooms: [{ room_code: 'B204', issued: 180 }, { room_code: 'A101', issued: 142 }, { room_code: 'C102', issued: 96 }, { room_code: 'B105', issued: 74 }], hourly_volume: [{ hour: '08', tickets: 22 }, { hour: '09', tickets: 38 }, { hour: '10', tickets: 29 }] }, navigation: { sessions_7d: 1402, off_route_events_7d: 12, completion_rate_7d: 94 }, offices: { issued_today: 74, completed_today: 51 }, engagement: { events_upcoming: 6, notifications_7d: 492 } };
  let alerts = [{ key: 'capacity', severity: 'critical', title: 'A queue needs attention', detail: 'The design studio line is above its configured waiting threshold.', target: '/admin/services' }, { key: 'anchor', severity: 'warning', title: 'An anchor needs verification', detail: 'Review the entrance anchor before the next campus session.', target: '/admin/spatial' }];
  const data: Record<string, unknown> = {
    '/me': { user, assignments: [] }, '/me/notifications': { items: notices, unread: 1 },
    '/student/dashboard': { user, next_class: entry, today: { entries: [entry, { ...entry, id: 'session-two', course_code: 'CS210', course_title: 'Data structures', starts_at_iso: '2026-09-15T14:00:00Z', ends_at_iso: '2026-09-15T15:30:00Z', room_code: 'A101' }] }, queue_ticket: ticket, office_ticket: null, quick_actions: [], unread_notifications: 1, notifications: notices, announcements: [{ id: 'a1', title: 'A new space to study', body: 'The learning centre welcomes students throughout the week.', priority: 'normal' }], events: [], building_alerts: [] },
    '/student/queues/board': { queues }, '/student/queue-tickets/active': { ticket },
    '/student/offices': { offices: [summary] }, '/student/office-tickets': { tickets: [] },
    '/student/timetable': { dates: ['2026-09-14','2026-09-15','2026-09-16','2026-09-17','2026-09-18'], week_start: '2026-09-14', week_end: '2026-09-20', entries: [entry] },
    '/campus/buildings': { buildings }, '/campus/buildings/b1': { building: buildings[0], floors: [], rooms: [] },
    '/campus/positioning/anchors': { anchors: [{ id: 'anchor1', nav_node_id: 'node1', code: 'A-ENTRANCE', label: 'Learning centre entrance', is_active: true }] }, '/student/positioning/current': { position: null }, '/ai/conversations': { conversations: [] }, '/ai/capabilities': { tool_count: 2, total_tools: 2, platform: 'web', tools: [{ id: 'locate_room', label: 'Find campus rooms', needs: 'campus.read' }, { id: 'my_schedule', label: 'Read your timetable', needs: 'timetable.read' }] },
    '/staff/dashboard': { kpis: { served_today: 24, waiting_now: 9, offices_open: 2 }, scopes: { queues: 2, offices: 1 }, campus_time: { date: '2026-09-15', time: '10:00:00' }, queues: [{ ...queues[0], queue_id: 'q1', occupying: 2, served_today: 18, current: { ticket_number: 'B-023', student_name: 'Alex Rivera', status: 'called' } }], offices: [{ ...office, office_id: 'o1', waiting: 3, in_service: 1, completed_today: 6, current: null }], pending_queue_actions: [{ id: 't1', ticket_number: 'B-024', student_name: 'Amina Yusuf', status: 'checked_in' }], pending_office_actions: [], teaching_today: [entry] },
    '/admin/dashboard': { kpis: { generated_at: now, students: 1840, waiting_now: 32, office_waiting_now: 12, issued_today: 146, average_wait_minutes: 12, navigation_sessions_today: 204, buildings: 3, rooms: 38 }, overview, live_queues: [{ ...queues[0], queue_id: 'q1', occupying: 2 }], recent_audit: [{ id: 'audit1', actor_name: 'Daniel Nwosu', action: 'queue.updated', entity_type: 'Room queue', created_at: now }], buildings },
    '/admin/users': { items: [user], meta: { page: 1, per_page: 25, total: 1, total_pages: 1 } }, '/admin/staff-assignments': { assignments: [] },
  };
  await page.route('**/api/v1/**', async (route) => {
    const path = new URL(route.request().url()).pathname.replace('/api/v1', '');
    if (path !== '/me' && failure) return route.fulfill({ status: 503, json: { success: false, message: 'The campus service is temporarily unavailable.' } });
    if (path === '/admin/alerts') return route.fulfill({ json: { success: true, data: { alerts, counts: { critical: alerts.filter((a) => a.severity === 'critical').length, warning: 1, acknowledged: 0 }, generated_at: now } } });
    if (path === '/admin/alerts/ack') { const { fingerprint } = route.request().postDataJSON(); alerts = alerts.filter((a) => a.key !== fingerprint); return route.fulfill({ json: { success: true, data: { acknowledged: fingerprint } } }); }
    if (path in data) return route.fulfill({ json: { success: true, data: data[path] } });
    return route.fulfill({ status: 503, json: { success: false, message: 'Review fixture: this resource is unavailable.' } });
  });
}
